### ISSUE TITLE
A aRenderFlex overflowed by 10 pixels on the right of first Dashboard Tile

### ISSUE THREAD

**Issue by PradeepYadav123** [prateekKrOraon/covid19_tracker#12]
Hi Prateek,

Thanks for such a wonderful app...
![Screenshot_2020-05-18-02-56-03-546_com tracker covid19_india covid19_tracker](https://user-images.githubusercontent.com/16350087/82160536-b1eeb300-98b3-11ea-99c4-3768f7940607.jpg)

I am getting UI issue A RenderFlex overflowed by 10 pixels on the right of first Dashboard Tile.
Could you please help to remove this issue.

Thanks
Pradeep Yadav

**Comment by prateekKrOraon** [comment]
Can you tell me what is your devices screen DPI?
Have this problem on a few devices with lower screen DPI otherwise fixed for most screen DPIs.

**Comment by PradeepYadav123** [comment]
Hi Prateek,

The Screen DPI is 403.
Resolution 1080 x 2160 pixels

Thanks for your kind reply and help.

**Comment by prateekKrOraon** [comment]
Fixed it. 
Update the project to the latest commit and run the app.

keeping the issue open for now, in case the problem persists.

**Comment by PradeepYadav123** [comment]
Thanks Prateek Its fine now.
