### ISSUE TITLE
More Analysis Tab data not showing

### ISSUE THREAD

**Issue by PradeepYadav123** [prateekKrOraon/covid19_tracker#16]
Please  check what is the issue we are not able to see data 
Please do the needful to fix.
![Screenshot_2020-05-20-01-24-18-443_com tracker covid19_india covid19_tracker](https://user-images.githubusercontent.com/16350087/82372104-ffe0f380-9a38-11ea-9d84-bd412a7cc9ce.jpg)

Thanks
Pradeep Yadav

**Comment by prateekKrOraon** [comment]
Solved.
Update master code.
